### ISSUE TITLE
Cannot add custom attributes to a flambe module

### ISSUE THREAD

**Issue by peterAsapp** [asappresearch/flambe#145]
**Describe the bug**
If you try to follow [this example](https://flambe.ai/en/v0.4.6/understanding/experiments.html#adding-custom-state), you get an error `Unexpected key(s) in state_dict`. This is b/c of a bug in this if clause: https://github.com/asappresearch/flambe/blob/aad135b6177713b786fdf07f08a4165ef0c1dfd4/flambe/compile/component.py#L1264-L1269

The else clause is never hit if `module` is `flambe.nn.Module` b/c it inherits from `torch.nn.Module`, and therefore any custom attribute is treated as an unexpected key.

**To Reproduce**
Follow the example in the doc.

**Expected behavior**
The custom attribute should be loaded correctly.

**Screenshots**

**Software Versions (please complete the following information):**
 - OS: macOS 10.14
 - Python Version: 3.6
 - PyTorch Version: 1.1
 - Flambé Version: 0.4.6

**Additional context**

**Comment by nmatthews-asapp** [comment]
Hey @peterAsapp nice catch, you are right that this error shouldn't be thrown, but the problem is actually misuse of the load method in the trainer. I'll try to explain why:
- The code you point out is actually correct; `_load_from_state_dict` in Pytorch will still call our hook. Notice in `Component.__init__` how we register the hook that appears in the else case. The hook mechanism is new in PyTorch 1.1+ I believe, and you can learn more by diving into the source code for `torch.nn.Module` if you're curious
- On the other hand, because our saving mechanism uses these hooks to add extra things to the state_dict that pytorch doesn't expect, one should basically always use `strict=False` when using either our state or PyTorch's native state dict methods. (see https://flambe.ai/en/v0.4.6/autoapi/flambe/compile/component/index.html#flambe.compile.component.Component.load_state)
- The error you see here is actually caused by `Trainer` not using `strict=False` when loading the weights of the best model. I'll submit a PR to fix this shortly.
